# Generated by Django 5.2.17 on 2026-08-31 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team or Unit Name, e.g. Alpha Rescue, Fire Unit 1', max_length=100)),
                ('zone', models.CharField(help_text='Assigned campus sector/zone', max_length=100)),
                ('incident_types', models.JSONField(default=list, help_text="List of handled incident types, e.g. ['medical', 'fire']")),
                ('availability_status', models.CharField(choices=[('on-duty', 'On Duty'), ('off-duty', 'Off Duty'), ('busy', 'Busy / Dispatched')], default='on-duty', max_length=20)),
                ('cases_handled', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average response time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'responder'}, on_delete=django.db.models.deletion.CASCADE, related_name='response_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cases_handled', 'name'],
            },
        ),
    ]
