# Generated by Django 6.1 on 2026-08-31 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(help_text='e.g. Campus Police, Medical Unit, Parent, Roommate', max_length=80)),
                ('phone_number', models.CharField(max_length=25)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_campus_service', models.BooleanField(default=False, help_text='Official 24/7 campus safety hotline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_campus_service', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('EMERGENCY', 'Emergency SOS'), ('MEDICAL', 'Medical Emergency'), ('ACCIDENT', 'Accident'), ('FIRE', 'Fire'), ('PHYSICAL_THREAT', 'Physical Threat'), ('SUSPICIOUS', 'Suspicious Activity'), ('INFRASTRUCTURE', 'Unsafe Infrastructure'), ('OTHER', 'Other')], default='EMERGENCY', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(default='Main Campus Grounds', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Low Urgency'), ('MEDIUM', 'Medium Urgency'), ('HIGH', 'High Urgency'), ('CRITICAL', 'Critical Urgency')], default='CRITICAL', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Team Accepted'), ('ON_THE_WAY', 'Team On The Way'), ('ARRIVED', 'Team Arrived'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('response_team_name', models.CharField(blank=True, max_length=120, null=True)),
                ('responder_notes', models.TextField(blank=True, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_sos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Team Accepted'), ('ON_THE_WAY', 'Team On The Way'), ('ARRIVED', 'Team Arrived'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(default='System', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='safety_app.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, help_text='e.g. SC-84920', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Your mobile contact', max_length=25)),
                ('dormitory_block', models.CharField(blank=True, help_text='e.g. West Campus, Hall B, Room 304', max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('', 'Select Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('medical_allergies', models.TextField(blank=True, help_text='Allergies, chronic conditions, regular medications')),
                ('emergency_notes', models.TextField(blank=True, help_text='Notes for first responders (e.g. asthma inhaler in bag)')),
                ('dark_mode', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('large_text', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('voice_assist', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
